---
- name: ensure git
  apt:
    name: git
    state: present
    force_apt_get: yes

- name: cloning pihole
  git:
    repo: "{{ pihole_repo }}"
    dest: "{{ pihole_directory }}"
    depth: "{{ pihole_repo_depth }}"
    version: "{{ pihole_branch }}"

- name: making directories
  file:
    path: "/etc/pihole/"
    state: directory
    mode: 0755

- name: pushing config file setupVars
  template:
    src: templates/setupVars.conf.j2
    dest: "/etc/pihole/setupVars.conf"
    mode: 0644

- name: installing pihole
  shell:
    chdir: "{{ pihole_directory }}/automated install/"
    cmd: "bash basic-install.sh --unattended"