- name: Install packages for StatusBoard Zero
  become: yes
  apt:
    pkg: "{{ required_packages }}"
    state: latest
    force_apt_get: yes

- name: Copy status script to local machine
  copy:
    src: /opt/ansible/files/status.py
    dest: "/home/{{ raspi_user }}/"
    force: yes

- name: Creates a crontab entry to load Status script
  cron:
    name: "StatusBoard"
    special_time: reboot
    job: "python /home/{{ raspi_user }}/status.py"
  notify: Reboot host
