---
# ref: https://github.com/dbcli/awscli/blob/v1.8.1/README.md#quick-start

- name: Ensure Pip is installed
  apt:
    pkg: "{{ pip_package }}"
    state: present
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: 3600
